---
title: "missing_videos"
author: "Florian Freitag"
date: "2023-11-15"
output: html_document
---
Script that takes a folder of matlabs and a folder containing  csv's with creation times and outputs a list of Trials that have matching (closets to, but no more than 5 seconds away) videos

adjust source, matpath and creapath


```{r}

library(R.matlab)
library(tidyverse)
library(purrr)


source("C:/Users/deepl/Desktop/missing_video_helper.r")

matpath = "C:/Users/deepl/Desktop/a/mat"
creapath = "C:/Users/deepl/Desktop/a/times"

```

```{r}
data <- mat_to_tibble(matpath)
data <- add_times(data)
creas <- load_creas_times(creapath)


data <- data %>% filter(name=='HIT') %>% select(id,Behv,Trial2,timediff)
```


```{r}
# Apply the matching function by group
creas2 <- creas %>%
  group_by(id) %>%
  group_map(~ match_within_group(.x, data %>% filter(id == .y$id[1])),.keep = T) %>%
  bind_rows()

to_keep <- creas2 %>% left_join(data %>% ungroup() %>% select(!id), by = join_by(closest_hit_time==timediff)) %>% select(!closest_hit_idx) %>% mutate(timediff = CreationTime-closest_hit_time)  %>% filter(abs(timediff) < 5) %>% mutate(video = sprintf("%03d", video))

to_keep
```




```{r}
library(dplyr)
library(tidyr)
# Define a function to process each group
process_group <- function(creas_times,timediff) {
  # Step 1: Create all combinations of rows between crea_time and sim
  combined_data <- crossing(creas_times, timediff)
  # Step 2: Calculate time differences
  combined_data <- combined_data %>%
    mutate(timediff2 = abs(creas_times- timediff))
  # Step 3: Filter out negative time differences
 
  # Step 4: Find the closest time difference for each entry in crea_time
  closest_times <- combined_data %>%
    group_by(creas_times) %>%
    slice(which.min(timediff2)) %>%
    ungroup()
  # Return the result
  closest_times
}

group_names <- unique(creas_times$group) # assuming you have a grouping variable
results <- list()
for (group in group_names) {
  # Subset data for the current group
  group_crea <- subset(creas_times, group == group)
  group_data <- subset(hits2, id == group)
  # Call the function for the current group
  result <- process_group(group_crea$CreationTime, group_data$timediff)
  result <- result %>% left_join(group_crea,by = c("creas_times" = "CreationTime")) %>%
  left_join(group_data, by = c("timediff" = "timediff"))
  # Store the result
  results[[group]] <- result
}
# Combine results into a single dataframe
final_result <- do.call(rbind, results)

final_result

group_names
group_crea <- subset(creas_times, id == '5_3')
group_data <- subset(hits2, id == '5_3')
  # Call the function for the current group
  result <- process_group(group_crea$CreationTime, group_data$timediff)
  # Store the result
  results[[group]] <- result
  
creas_times%>% filter(id == '4_1')
final_result %>% select(id.x,Trial,video)

hits2 %>% filter(id =='4_1')

final_result %>% filter(id.x == '4_1') %>% arrange(video)

creas_times

filter <- final_result %>% filter(Behv =='W2T') %>% select(video,id,Trial2) %>% mutate(newvid = sprintf("%03d", video)) %>% mutate(pre = 'mm') %>% unite('filt1',pre,id,sep="") %>% unite('filt', filt1,newvid)

#filter %>% write_csv("Filter.csv")

hits2

```


```{r}
hits3 <- hits2 %>% filter(id == 'M1_1')
creas <- creas_times %>% filter(group == 'M1_1')
hits3

matched_hits <- integer(0)

# Custom function to find the closest unmatched hit timestamp
find_closest_unmatched <- function(crea_time, hit_times, matched_hits) {
  # Filter out the matched hits
  unmatched_hits <- setdiff(seq_along(hit_times), matched_hits)
  
  # Find the closest hit among the unmatched ones
  closest_idx <- unmatched_hits[which.min(abs(hit_times[unmatched_hits] - crea_time))]
  return(closest_idx)
}
creas

# Iterate over each crea_time and find the closest unmatched hit
creas2 <- creas %>%
  rowwise() %>%
  mutate(closest_hit_idx = find_closest_unmatched(CreationTime, hits3$timediff, matched_hits),
         matched_hits = list(append(matched_hits, closest_hit_idx)))
creas2
# Extract the corresponding hit timestamps and clean up the dataframe
creas2 %>%
  ungroup() %>%
  mutate(closest_hit_time = hits3$timediff[closest_hit_idx]) %>%
  select(-closest_hit_idx, -matched_hits)
```



