---
title: "try matlab"
author: "Florian Freitag"
date: "2023-11-15"
output: html_document
---

# Read raw Data

```{r}
library(R.matlab)
library(tidyverse)
library(purrr)

list_files <- list.files(path = "C:/Users/freit/Desktop/mat",full.names = TRUE)
myfiles = lapply(list_files, readMat)



datalist = myfiles
match <- tibble(column_label =as.character(c(1,2,3,4,5,6,7,8,9)), mouse=c(4,4,4,5,5,5,6,6,6), day=c(1,2,3,1,2,3,1,2,3))


list2 <- list.files(path = "C:/Users/freit/Desktop/times",full.names = TRUE)
creas <- read_csv(list2,id = "group")

creas_times <- creas %>% group_by(group) %>%  mutate(column_label = as.character(cur_group_id())) %>% arrange(column_label,CreationTime) %>% mutate(video = row_number()) %>% ungroup %>% select(!c(FilePath,group)) %>% left_join(match) %>% unite('id', mouse,day)

creas_times

Aa <- list.files(path = "C:/Users/freit/Desktop/mat")
Ab <- list.files(path = "C:/Users/freit/Desktop/times")
creas_times %>% distinct(id)
Aa
Ab
```

#Raw data to tibble

```{r}
flist = list()
times <- list()
for (x in 1:length(datalist))
{
i=1
data <- datalist[[x]]
time <- hms::as_hms(data[["SessionData"]][[2]][[6]])
dat <- data[[1]][[4]][[1]]
df=tibble()
  for (i in 1:dim(dat)[2])
   {
    zz <- dat %>% flatten()  %>% pluck(i,1) %>%  enframe() %>%   unnest_wider(value,names_sep="_",names_repair='unique')
    df <- rbind(df,tibble(name = zz$name, start=zz$value_1[,1], end=zz$value_1[,2],Trial=i))
flist[[x]] = df   
  }
times[[x]]= time
}

st <- tibble(column_label =as.character(c(1,2,3,4,5,6,7,8,9)), mouse=c(4,4,4,5,5,5,6,6,6), day=c(1,2,3,1,2,3,1,2,3),times = times)  %>% unnest_longer(col = times)




df <- bind_rows(flist, .id = "column_label") %>% na.omit() %>% left_join(match) %>% left_join(st) 

Data2 <- df %>% unite('Trial2',c(mouse,day,Trial),remove=F) %>% group_by(Trial2) %>%  mutate(Behv = case_when(
  'Audio' %in% name ~ "W2T",
  'Airpuff' %in% name ~ "A2L",
  'Audio2Air' %in% name ~"PC",
  .default = "WTF")) %>% mutate(succ = ifelse('HIT' %in% name,'Hit','Miss')) %>% ungroup() %>% unite('id',mouse,day)

hits <- Data2 %>% group_by(id) %>% mutate(len = end - start) %>% mutate(cumsec = round(cumsum(len),2), cum2 = hms::as_hms(cumsec), timediff = hms::as_hms(cum2 + times))%>% filter( succ == "Hit")
```

#for videos

```{r}
hits2 <- hits %>% group_by(Trial2) %>% filter(name=='HIT')

hits2 
creas_times

hits %>% group_by(Trial2) %>% filter(name=='HIT') %>% filter(id =='5_3')
subset(hits2, id == '5_3')
```

```{r}
library(dplyr)
library(tidyr)
# Define a function to process each group
process_group <- function(creas_times,timediff) {
  # Step 1: Create all combinations of rows between crea_time and sim
  combined_data <- crossing(creas_times, timediff)
  # Step 2: Calculate time differences
  combined_data <- combined_data %>%
    mutate(timediff2 = abs(creas_times- timediff))
  # Step 3: Filter out negative time differences
 
  # Step 4: Find the closest time difference for each entry in crea_time
  closest_times <- combined_data %>%
    group_by(creas_times) %>%
    slice(which.min(timediff2)) %>%
    ungroup()
  # Return the result
  closest_times
}

group_names <- unique(creas_times$id) # assuming you have a grouping variable
results <- list()
for (group in group_names) {
  # Subset data for the current group
  group_crea <- subset(creas_times, id == group)
  group_data <- subset(hits2, id == group)
  # Call the function for the current group
  result <- process_group(group_crea$CreationTime, group_data$timediff)
  result <- result %>% left_join(group_crea,by = c("creas_times" = "CreationTime")) %>%
  left_join(group_data, by = c("timediff" = "timediff"))
  # Store the result
  results[[group]] <- result
}
# Combine results into a single dataframe
final_result <- do.call(rbind, results)



group_names
group_crea <- subset(creas_times, id == '5_3')
group_data <- subset(hits2, id == '5_3')
  # Call the function for the current group
  result <- process_group(group_crea$CreationTime, group_data$timediff)
  # Store the result
  results[[group]] <- result
  
creas_times%>% filter(id == '4_1')
final_result %>% select(id.x,Trial,video)

hits2 %>% filter(id =='4_1')

final_result %>% filter(id.x == '4_1') %>% arrange(video)

creas_times

filter <- final_result %>% filter(Behv =='W2T') %>% select(video,id.x,Trial2) %>% mutate(newvid = sprintf("%03d", video)) %>% mutate(pre = 'mm') %>% unite('filt1',pre,id.x,sep="") %>% unite('filt', filt1,newvid)

filter %>% write_csv("Filter.csv")


```



