---
title: "Waveform_analysis"
output: html_document
date: "2025-02-04"
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse)
source("C:/Users/Freitag/Documents/GitHub/Master_thesis/Analysis/Analysis/Master_helper.R")
```

# load data - non Opto
```{r}
Trialless <- read_csv("E:/Florian_paper/Florian/Aligned_Data/Analysable_data/wrangled_Data/R_outputs/Trialless.csv")



metapath = "E:/Florian_paper/Florian/Aligned_Data/Analysable_data/meta"
list_of_meta <- list.files(path = metapath,
                             pattern = "\\.tsv$",
                             full.names = TRUE)
 meta <- read_tsv(list_of_meta, id = 'id2') %>%  as_tibble()%>% select(id2,cluster_id,n_spikes,depth,group,fr)
meta <- meta %>% mutate(id = str_extract(meta$id2, "M\\d+_\\d+"))

list_of_ptt <- list.files(path = "E:/Florian_paper/Florian/Aligned_Data/Analysable_data/peak_to_trough_times",
                             pattern = "\\.csv$",
                             full.names = TRUE)
ptt <- read_csv(list_of_ptt, id = 'id2') %>%  as_tibble()

translator <- read_csv2("E:/Florian_paper/Florian/Aligned_Data/Analysable_data/translator.csv")

Trialless <- Trialless %>%  left_join(meta %>% left_join(ptt %>% separate(Original_Index, into = c("old", "second_part"), sep = "(?=_row)", extra = "merge", remove = FALSE) %>% left_join(translator) %>% select(second_part:new) %>% select(!Folder) %>% separate_wider_delim(second_part, delim ='_' ,names =c('d1','d2','cluster_id')) %>% select(cluster_id:new) %>% rename(id = new) %>% mutate(cluster_id = as.numeric(cluster_id)) %>% filter(`Peak_to_Valley (ms)` > 0)) %>% replace_na(list(`Peak_to_Valley (ms)`=0)) %>% mutate(newgroup = ifelse(`Peak_to_Valley (ms)`==0,group,'FS')) %>% filter(group!= 'noise', newgroup!= 'noise')) %>% select(Behv:Zscore, newgroup) %>% filter(newgroup!= 'noise')
```

# Plot - non Opto
```{r}
Trialless

    ord <- Trialless  %>% filter(between(rel_time,0,0.1)) %>% group_by(cluster_id2)  %>%
      filter(Behv == 'A2L') %>% group_by(cluster_id2) %>%
      summarise(ord = mean(Zscore)) %>%   arrange( ord)  %>% mutate(cluster_id2 = as.factor(cluster_id2)) %>% pull(cluster_id2)
  
  
  
  
  # z score and filter
  g1 <- Trialless  %>% filter(between(rel_time,-0.1,0.25)) %>% select(Behv,cluster_id2,Zscore,rel_time,newgroup)
  

  
  #apply order 
  g1$cluster_id2 <- factor(g1$cluster_id2, levels = ord)
  g1 <- g1 %>% mutate(newgroup = case_when(
    newgroup=='FS'~'FS',
    newgroup=='good'~'regular',
    newgroup=='mua'~'inverted',
    .default = 'Fuck'))
  
  #heatmap
  map <-g1 %>% mutate(Zscore= ifelse(Zscore > 12,12,Zscore))%>% ggplot(aes(rel_time,cluster_id2,fill=Zscore))+
    geom_raster()+
    geom_vline(xintercept = 0, col ='grey',linetype = 'dashed')+
    facet_grid(newgroup~Behv,scales = 'free',space = "free",switch = "y")+
    scale_fill_gradientn(colors = c("darkblue",'beige' ,"beige", "red"),
                       values = scales::rescale(c(min(g1$Zscore), -0.65, 0, 12)),
                       guide = guide_colorbar(
                         ticks = FALSE,  # Remove intermediate ticks
                        draw.ulim = FALSE,     # Remove top tick
                         draw.llim = FALSE,   
                        
                       ),
                       breaks = c(-2, 12))+
    theme_void()+
    theme(plot.margin = unit(c(0.1,0.2,0,0.7), 'lines'),
          strip.text.x = element_text(size = 34),
          strip.text.y = element_text(size = 34,angle = 90,margin = margin(r = 8)),
          legend.text = element_text(size = 18),
          legend.title = element_text(size = 22),
          panel.clip='off')+
    labs(fill='Z- scored FR')+
    guides(fill = guide_colorbar(barheight = 10, barwidth = 2, ticks = FALSE)) 
  
   #activity across all units
  smo <- g1 %>% group_by(Behv,rel_time,newgroup) %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4,fill = 'black')+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    facet_grid(newgroup~Behv,,switch = "y")+
    theme_minimal()+
    theme(plot.margin = unit(c(0.1,0.2,0,0.7), 'lines'),
          strip.background = element_blank(),
          strip.text = element_blank(),
          axis.text.y = element_blank(),
           axis.text.x=element_text(size=16),
          axis.title=element_text(size=30))+
    xlab("time from stimulus")+
    ylab("Z-scored FR")

  # arrange plots
  plot <- ggpubr::ggarrange(map, smo, heights = c(2, 0.8),vjust= c(0.5,0.5),
                    ncol = 1, nrow = 2, align = "v",common.legend=T,legend = 'right')
  print(plot)

  library(export)
x11() # open graphics window
# now maximize this window so it is full screen


print(plot)
graph2tif(x= plot, file='C:/Users/Freitag/Desktop/waveform_v2',
         width = dev.size(units="px")[[1]]/90,
         height = dev.size(units="px")[[2]]/90,
         dpi = 900)

dev.off()

# g1 %>% distinct(cluster_id2, newgroup) %>% count(newgroup)
#   

?facet_grid
  
  
   g1 %>% group_by(Behv,rel_time,newgroup) %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4,fill = 'black')+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    facet_grid(newgroup~Behv)+
    theme_minimal()+
    theme(plot.margin = unit(c(0.1,0.2,0,1), 'lines'),
          strip.text = element_blank(),
          axis.text=element_blank(),
          axis.title=element_text(size=16))+
    xlab("time from stimulus")+
    ylab("Z-scored FR")
   
   g1 %>% distinct(newgroup)
   
   
library(patchwork)
   
ggrastr::rasterize(map) / smo + plot_layout(heights = c(2, 0.8), guides = "collect") & theme(legend.position = "right")
ggrastr::rasterize(map) / smo + plot_layout(heights = c(2, 2), guides = "collect") & theme(legend.position = "right")


g1 %>% group_by(Behv,rel_time,newgroup) %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4,fill = 'black')+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    facet_grid(newgroup~Behv,,switch = "y")+
    theme_minimal()+
    theme(plot.margin = unit(c(0.1,0.2,0,0.7), 'lines'),
           axis.text=element_text(size=16),
          axis.title=element_text(size=30))+
    xlab("time from stimulus")+
    ylab("Z-scored FR")

g1 %>% ggplot(aes(newgroup,Zscore))+
  geom_boxplot()

g1 %>% filter(between(rel_time,0,0.03))  %>% group_by(cluster_id2) %>% slice_max(Zscore)  %>% group_by(newgroup) %>% summarise(median = median(Zscore),mean= mean(Zscore), low = quantile(Zscore,0.25), high =  quantile(Zscore,0.75), bot = max( min(Zscore), (low-mean)*1.5), top = min( max(Zscore), mean+high*1.5)) %>% 
  ggplot(aes(newgroup,mean))+
  geom_pointrange(aes(ymax=high, ymin = low))+
   geom_boxplot(
    stat = "identity",
    aes(lower  = low,
        upper  = high,
        middle = mean,
        ymin   = bot, # optional
        ymax   = top) # optional
  )



g1 %>% filter(between(rel_time,0,0.04)) %>% group_by(cluster_id2) %>% slice_max(Zscore) %>% group_by(newgroup) %>% summarise(median = median(Zscore),mean= mean(Zscore), low = quantile(Zscore,0.25), high =  quantile(Zscore,0.75), bot = max( min(Zscore), (low-mean)*1.5), top = min( max(Zscore), mean+high*1.5)) %>% 
  ggplot(aes(newgroup,mean))+
  geom_pointrange(aes(ymax=high, ymin = low))+
   geom_boxplot(
    stat = "identity",
    aes(lower  = low,
        upper  = high,
        middle = median,
        ymin   = bot, # optional
        ymax   = top) # optional
  )



g1 %>% group_by(Behv,rel_time,newgroup) %>% filter(Behv == 'A2L') %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4,fill = 'black')+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    facet_grid(~newgroup,,switch = "y")+
    theme_minimal()+
    theme(plot.margin = unit(c(0.1,0.2,0,0.7), 'lines'),
           axis.text=element_text(size=16),
          axis.title=element_text(size=30))+
    xlab("time from stimulus")+
    ylab("Z-scored FR")



plotly::ggplotly(
 g1 %>% group_by(Behv,rel_time,newgroup) %>% filter(Behv == 'A2L') %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3,col=newgroup,fill=newgroup))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4)+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    theme_minimal()+
    theme(plot.margin = unit(c(0.1,0.2,0,0.7), 'lines'),
           axis.text=element_text(size=16),
          axis.title=element_text(size=30))+
    xlab("time from stimulus")+
    ylab("Z-scored FR")

)

g1 %>% group_by(Behv,rel_time,newgroup) %>% filter(Behv == 'A2L') %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3,col=newgroup,fill=newgroup))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4)+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    theme_minimal()+
    theme(plot.margin = unit(c(0.1,0.2,0,0.7), 'lines'),
           axis.text=element_text(size=16),
          axis.title=element_text(size=30))+
    xlab("time from stimulus")+
    ylab("Z-scored FR")
ggsave('C:/Users/Freitag/Desktop/AA.tif', dpi = 900 , bg ='white')



g1 %>% group_by(Behv,rel_time,newgroup) %>% filter(Behv == 'A2L') %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3,col=newgroup,fill=newgroup))+
   geom_smooth(span=0.18)+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    theme_minimal()+
    theme(plot.margin = unit(c(0.1,0.2,0,0.7), 'lines'),
           axis.text=element_text(size=16),
          axis.title=element_text(size=30))+
    xlab("time from stimulus")+
    ylab("Z-scored FR")

Trialless %>% distinct(cluster_id2,newgroup) %>% count(newgroup)
```

# Waveform stats
```{r}

Trialless

Trialless <- Trialless %>% left_join(Trialless %>% filter(rel_time < 0) %>% group_by(Behv,newgroup) %>% summarise(bl = mean(Zscore))) %>% ungroup %>% mutate(Zscore = Zscore - bl)

Test4_org <- Trialless  %>%  distinct(newgroup,rel_time,Behv,Zscore, cluster_id2,id)%>% filter(between(rel_time,0,0.04))  %>%  group_by(newgroup,cluster_id2,Behv) %>% slice_max(Zscore) %>% distinct(newgroup,Behv,cluster_id2,id,Zscore) %>% separate_wider_delim(id, names = c('Mouse','Session'), delim = '_') %>% ungroup %>% na.omit()

Test4 <- Test4_org %>%  mutate(Zscore = Zscore - min(Zscore) +1) %>% mutate(across(c(newgroup,Behv,Mouse,Session), as.factor))

mod3 <-lme4::glmer(data= Test4, Zscore ~ Behv + newgroup + Behv*newgroup + (1 |Mouse) + (1 | Mouse:Session), family =  Gamma(link='inverse'))
mod0 <-lme4::glmer(data= Test4, Zscore ~ 1 + (1 |Mouse) + (1 | Mouse:Session), family =  Gamma(link='inverse'))

anova(mod3,mod0)


res <- DHARMa::simulateResiduals(fittedModel = mod3, plot = T,refit=F,use.u = T)
DHARMa::plotQQunif(res, testUniformity = F,testOutliers = F,testDispersion = F)




library(emmeans)

g<-emmeans::emmeans(mod3, pairwise ~ newgroup)
g$contrasts %>% as_tibble()
g$emmeans %>% as_tibble()
# layer conditional
laycon <- emmeans(mod3, pairwise ~newgroup| Behv)
laycon




emmeans_Behv_simp <- emmeans::emmeans(mod3, ~ newgroup|Behv , type = "response",weights = 'proportional')
behvcon_simp <- emmeans::emmeans(mod3, pairwise ~ newgroup|Behv, weights = 'proportional')
# Convert to tibble
pdata <- emmeans_Behv_simp %>% as_tibble() %>% mutate(newgroup = as.character(newgroup)) %>% filter(Behv == 'A2L')
pdata <- pdata %>% mutate(newgroup = trimws(as.character(newgroup)))

# Prepare p-values
pvals <- behvcon_simp$contrasts %>%
  as_tibble() %>% filter(Behv == 'A2L') %>% 
  separate_wider_delim(contrast, names = c("group1", "group2"), delim = "-") %>%
  mutate(psig = case_when(
    p.value < 0.001 ~'***',
    p.value < 0.01 ~'**',
    p.value < 0.05 ~'*',
     p.value > 0.05  ~'NS',
  )) %>%
  mutate(group1 = as.character(group1), group2 = as.character(group2))  %>% mutate(group1 = trimws(group1), group2 = trimws(group2)) %>%  # Ensure character type
  left_join(pdata %>% mutate(newgroup = as.character(newgroup)), 
            by = join_by(group1 == newgroup))

# Plot
 ggplot(pdata %>% mutate(response = response + min(Test4_org$Zscore)-1, asymp.LCL = asymp.LCL  + min(Test4_org$Zscore)-1, asymp.UCL = asymp.UCL  + min(Test4_org$Zscore)-1) %>% mutate(newgroup = case_when(
    newgroup=='FS'~'FS',
    newgroup=='good'~'RS',
    newgroup=='mua'~'inverted',
    .default = 'Fuck')) %>% mutate(newgroup= factor(newgroup, levels=c("FS", "inverted","RS"))), aes(x = newgroup, y = response)) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.2,  linewidth =1.3) +
  geom_point()+
  geom_text(aes(label = round(response, 2)), hjust = -0.5,size=5) +
  theme_minimal()+
  ylab('max Zscore response')+
  ggpubr::stat_pvalue_manual(pvals %>% mutate(response = response + min(Test4_org$Zscore)-1, asymp.LCL = asymp.LCL  + min(Test4_org$Zscore)-1, asymp.UCL = asymp.UCL  + min(Test4_org$Zscore)-1)  %>% mutate(group1 = case_when(
    group1=='FS'~'FS',
    group1=='good'~'RS',
    group1=='mua'~'inverted',
    .default = 'Fuck')) %>% mutate(group2 = case_when(
    group2=='FS'~'FS',
    group2=='good'~'RS',
    group2=='mua'~'inverted',
    .default = 'Fuck')) %>%  mutate(y.position = asymp.UCL + 0.3, y.position = ifelse(group1=='FS' & group2=='inverted', y.position+0.4,y.position)), label = "psig", 
                             xmin = "group1", xmax = "group2", y.position = "y.position", size=8,bracket.size=1)+
  coord_fixed(ratio=0.3)
ggsave('C:/users/Freitag/Desktop/waveform_stats.tiff', bg= 'white',dpi=900)


 

boxdata <- Test4_org  %>% group_by(newgroup) %>%
  summarise(min = max(quantile(Zscore, probs = 0),quantile(Zscore, probs = 0.25)*1.5),
            lower = quantile(Zscore, probs = 0.25),
            median = quantile(Zscore, probs = 0.5),
            mean = mean(Zscore),
            higher = quantile(Zscore, probs = 0.75),
            max = min(quantile(Zscore, probs = 1),quantile(Zscore, probs = 0.75)*1.5))

ggplot(boxdata, aes(x=newgroup, ymin = min, lower = lower, middle = mean, upper = higher, ymax = max)) +
  geom_boxplot(stat = "identity")+
  theme_minimal()+
   ggpubr::stat_pvalue_manual(pvals  %>% mutate(y.position = boxdata$max + 0.3, y.position = ifelse(group1=='FS' & group2=='mua', y.position+1.5,y.position)) %>% select(group1,group2,psig,y.position) %>% bind_cols(boxdata), label = "psig", 
                             xmin = "group1", xmax = "group2", y.position = "y.position")
  coord_fixed(ratio=0.2)
  
? ggpubr::stat_pvalue_manual
  
pr <-  Test4_org %>%  filter(newgroup != 'mua') %>% group_by(newgroup) %>% summarise( mean = mean(Zscore), median = median(Zscore))
  
  Test4_org %>% filter(newgroup != 'mua') %>% ggplot()+
    geom_density(aes(Zscore,col= newgroup))+
    geom_vline(data=pr,aes(xintercept = mean,col= newgroup, linetype ='1' ))+
    geom_vline(data=pr,aes(xintercept = median,col= newgroup, linetype ='2' ))
  
 Test4_org %>% ggplot(aes(newgroup,Zscore))+
   geom_boxplot()
 
 
Test4_org %>% group_by(newgroup) %>% summarise(Zm = mean(Zscore)) %>% mutate(norm_to_RS = Zm/3.319380, perc_change=  round(-(1- Zm/3.319380)*100,2))

jtools::effect_plot(mod3, pred = newgroup)
emmeans::emmeans(mod3, ~ newgroup , type = "response")

g<-emmeans::emmeans(mod3, ~ newgroup,type='response')
g%>% as_tibble() %>% ggplot(aes(newgroup,response))+
  geom_errorbar(aes(ymin=asymp.LCL, ymax=asymp.UCL))
emmeans::emmeans(mod3, pairwise~newgroup)



```

# depth plot - non Opto 
```{r}

Trialless <- add_layers(Trialless,"D:/Florian_paper/Florian/Aligned_Data/Analysable_data/depths")
   ord <- Trialless %>% filter(between(dist_surf,-50,1210))  %>% distinct(cluster_id2, dist_surf) %>%   arrange(dist_surf)  %>% mutate(cluster_id2 = as.factor(cluster_id2)) %>% pull(cluster_id2)
  
  
  
  
  
  # z score and filter
  g1 <- Trialless %>% filter(between(dist_surf,-50,1210)) %>% filter(between(rel_time,-1,1)) %>% select(Behv,cluster_id2,Zscore,rel_time,newgroup)
  

  
  #apply order 
  g1$cluster_id2 <- factor(g1$cluster_id2, levels = ord)
  
  
  #heatmap
  map <-g1 %>% ggplot(aes(rel_time,cluster_id2,fill=Zscore))+
    geom_tile()+
    geom_vline(xintercept = 0, col ='grey',linetype = 'dashed')+
    facet_grid(newgroup~Behv,scales = 'free',space = "free")+
    scale_fill_gradient2(low = 'darkblue', mid = 'beige', high = 'red', midpoint = 0, limits = c(round(min(g1$Zscore)), round(max(g1$Zscore)*0.5)), breaks = c(round(min(g1$Zscore)),  round(max(g1$Zscore)*0.5)) ,na.value = "darkred")+
    theme_void()+
    theme(plot.margin = unit(c(0,0.2,0,1), 'lines'),
          strip.text.x = element_text(size = 30))+
    labs(fill='Z- scored FR') 
  
   #activity across all units
  smo <- g1 %>% group_by(Behv,rel_time,newgroup) %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4,fill = 'black')+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    facet_grid(newgroup~Behv)+
    theme_minimal()+
    theme(plot.margin = unit(c(0.1,0.2,0,1), 'lines'),
          strip.background = element_blank(),
          strip.text.x = element_blank(),
          axis.text=element_text(size=12),
          axis.title=element_text(size=20,face="bold"))+
    xlab("time from stimulus")+
    ylab("Z-scored FR")
  
  # arrange plots
  plot <- ggpubr::ggarrange(map, smo, heights = c(2, 0.8),vjust= c(0.5,0.5),
                    ncol = 1, nrow = 2, align = "v",common.legend=T,legend = 'right')
  plot
  
g2 <- Trialless %>% filter(Behv =='A2L') %>% filter(between(dist_surf,-50,1210)) %>% filter(between(rel_time,-1,1)) %>% select(Layer,Layer_fine,cluster_id2,Zscore,rel_time,newgroup)
txtx =  g2  %>% distinct(cluster_id2, Layer, newgroup) %>% group_by(Layer,newgroup) %>% count()
   g2 %>% group_by(Layer,rel_time,newgroup) %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4,fill = 'black')+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    facet_grid(Layer~newgroup)+
    theme_minimal()+
     geom_text(data=txtx, aes(x=1.8, y=5, label=n), 
            colour="black", inherit.aes=FALSE, parse=FALSE)
```

# load data -  Opto
```{r}
Trialless <- read_csv("E:/Florian_paper/Florian/Aligned_Data/otpo/wrangled_Data/Trialless.csv")


metapath = "E:/Florian_paper/Florian/Aligned_Data/otpo/meta"
list_of_meta <- list.files(path = metapath,
                             pattern = "\\.tsv$",
                             full.names = TRUE)
 meta <- read_tsv(list_of_meta, id = 'id2') %>%  as_tibble()%>% select(id2,cluster_id,n_spikes,depth,group,fr)
  meta <- meta %>% mutate(id = str_extract(meta$id2, "O\\d+_[A-Za-z0-9]"))
  


list_of_ptt <- list.files(path = "E:/Florian_paper/Florian/Aligned_Data/otpo/PTT_times",
                             pattern = "\\.csv$",
                             full.names = TRUE)
ptt <- read_csv(list_of_ptt, id = 'id2') %>%  as_tibble()

translator <- read_csv2("C:/Users/Freitag/Desktop/folder_contents.csv")

Trialless <- Trialless %>%  left_join(meta %>% left_join(ptt %>% separate(Original_Index, into = c("new", "second_part"), sep = "(?=_row)", extra = "merge", remove = FALSE)  %>% select(new:`Peak_to_Valley (ms)`)  %>% separate_wider_delim(second_part, delim ='_' ,names =c('d1','d2','cluster_id')) %>% select(new,cluster_id,`Peak_to_Valley (ms)`) %>% rename(id = new) %>% mutate(cluster_id = as.numeric(cluster_id)) %>% filter(`Peak_to_Valley (ms)` > 0)) %>% replace_na(list(`Peak_to_Valley (ms)`=0)) %>% mutate(newgroup = ifelse(`Peak_to_Valley (ms)`==0,group,'FS')) %>% filter(group!= 'noise', newgroup!= 'noise')) %>% select(Behv:Zscore, newgroup) %>% filter(newgroup!= 'noise') %>% filter(Behv2 %in% c('Airpuff','Opto_Air','just_opto'))

Trialless %>% count(Behv)
```
# Plot - Optp
```{r}
  ord <- Trialless %>% filter(phase=='cortex')  %>% filter(between(rel_time,0,0.1)) %>% group_by(cluster_id2)  %>%
      filter(Behv == 'Airpuff') %>% group_by(cluster_id2) %>%
      summarise(ord = mean(Zscore)) %>%   arrange( ord)  %>% mutate(cluster_id2 = as.factor(cluster_id2)) %>% pull(cluster_id2)
  
  
  
  
  
  # z score and filter
  g1 <-  Trialless %>% filter(phase=='cortex') %>% filter(between(rel_time,-1,1)) %>% select(Behv,cluster_id2,Zscore,rel_time,newgroup)
  g1 <- g1 %>% group_by(newgroup) %>% complete(Behv,nesting(cluster_id2, rel_time), fill = list(Zscore = 0.1)) %>% filter(newgroup != 'NA')

g1 %>% group_by(Behv) %>% distinct(Behv,cluster_id2) %>% count()
  ?complete
  #apply order 
  g1$cluster_id2 <- factor(g1$cluster_id2, levels = ord)
  
  
  #heatmap
  map <-g1 %>% ggplot(aes(rel_time,cluster_id2,fill=Zscore))+
    geom_tile()+
    geom_vline(xintercept = 0, col ='grey',linetype = 'dashed')+
    facet_grid(newgroup~Behv,scales = 'free',space='free')+
    scale_fill_gradient2(low = 'darkblue', mid = 'beige', high = 'red', midpoint = 0, limits = c(round(min(g1$Zscore)), round(max(g1$Zscore)*0.5)), breaks = c(round(min(g1$Zscore)),  round(max(g1$Zscore)*0.5)) ,na.value = "darkred")+
    theme_void()+
    theme(plot.margin = unit(c(0,0.2,0,1), 'lines'),
          strip.text.x = element_text(size = 30))+
    labs(fill='Z- scored FR') 
  
   #activity across all units
  smo <- g1 %>% group_by(Behv,rel_time,newgroup) %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4,fill = 'black')+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    facet_grid(newgroup~Behv)+
    theme_minimal()+
    theme(plot.margin = unit(c(0.1,0.2,0,1), 'lines'),
          strip.background = element_blank(),
          strip.text.x = element_blank(),
          axis.text=element_text(size=12),
          axis.title=element_text(size=20,face="bold"))+
    xlab("time from stimulus")+
    ylab("Z-scored FR")
  
  # arrange plots
  plot <- ggpubr::ggarrange(map, smo, heights = c(2, 0.8),vjust= c(0.5,0.5),
                    ncol = 1, nrow = 2, align = "v",common.legend=T,legend = 'right')
  plot

  library(export)
# x11() # open graphics window
# # # now maximize this window so it is full screen
# # 
# #  
# print(plot)
# graph2png(x= plot, file='C:/Users/Freitag/Desktop/waveform',
#          width = dev.size(units="px")[[1]]/90,
#          height = dev.size(units="px")[[2]]/90,
#          dpi = 900)
# 
# dev.off() 
# 
# g1 %>% distinct(cluster_id2, newgroup) %>% count(newgroup)
#   


ord <- Trialless %>% filter(phase=='Thalamus')  %>% filter(between(rel_time,0,0.1)) %>% group_by(cluster_id2)  %>%
      filter(Behv == 'Airpuff') %>% group_by(cluster_id2) %>%
      summarise(ord = mean(Zscore)) %>%   arrange( ord)  %>% mutate(cluster_id2 = as.factor(cluster_id2)) %>% pull(cluster_id2)
  
  
  
  
  
  # z score and filter
  g1 <-  Trialless %>% filter(phase=='Thalamus') %>% filter(between(rel_time,-1,1)) %>% select(Behv,cluster_id2,Zscore,rel_time,newgroup)
  

  
  #apply order 
  g1$cluster_id2 <- factor(g1$cluster_id2, levels = ord)
  
  
  #heatmap
  map <-g1 %>% ggplot(aes(rel_time,cluster_id2,fill=Zscore))+
    geom_tile()+
    geom_vline(xintercept = 0, col ='grey',linetype = 'dashed')+
    facet_grid(newgroup~Behv,scales = 'free',space='free')+
    scale_fill_gradient2(low = 'darkblue', mid = 'beige', high = 'red', midpoint = 0, limits = c(round(min(g1$Zscore)), round(max(g1$Zscore)*0.5)), breaks = c(round(min(g1$Zscore)),  round(max(g1$Zscore)*0.5)) ,na.value = "darkred")+
    theme_void()+
    theme(plot.margin = unit(c(0,0.2,0,1), 'lines'),
          strip.text.x = element_text(size = 30))+
    labs(fill='Z- scored FR') 
  
   #activity across all units
  smo <- g1 %>% group_by(Behv,rel_time,newgroup) %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4,fill = 'black')+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    facet_grid(newgroup~Behv)+
    theme_minimal()
    theme(plot.margin = unit(c(0.1,0.2,0,1), 'lines'),
          strip.background = element_blank(),
          strip.text.x = element_blank(),
          axis.text=element_text(size=12),
          axis.title=element_text(size=20,face="bold"))+
    xlab("time from stimulus")+
    ylab("Z-scored FR")
  
  # arrange plots
  plot <- ggpubr::ggarrange(map, smo, heights = c(2, 0.8),vjust= c(0.5,0.5),
                    ncol = 1, nrow = 2, align = "v",common.legend=T,legend = 'right')
  plot
```

# depth plot - Opto 
```{r}
list_of_depth <- list.files(path = "D:/Florian_paper/Florian/Aligned_Data/otpo/depths",
                              pattern = "\\.csv$",
                              full.names = TRUE)
  depth <- read_csv(list_of_depth, id = 'id',col_names = F)
  depth <- depth %>% mutate(id = str_extract(depth$id, "O\\d+_[A-Za-z0-9]")) %>% rename('surface'=X1)
  
  
  Layerd <- Trialless%>% separate_wider_delim(cluster_id2, delim ='_', names = c('del', 'Mouse','Day'), cols_remove = F) %>% unite('id', c(Mouse,Day)) %>%
    select(!del) %>% 
    left_join(depth) %>% replace_na(list(surface = 950)) %>% 
    mutate(dist_surf = surface - depth) %>% 
    mutate(Layer_fine = case_when(
      between(dist_surf,-500,-20) ~ 'out',
      between(dist_surf,-20,50) ~ 'L1',
      between(dist_surf,50,500) ~ 'L2/3',
      between(dist_surf,500,750) ~ 'L5A',
      between(dist_surf,750,1050) ~ 'L5B',
      between(dist_surf,1050,1210) ~ 'L6',
      .default = "WTF"
    )) %>% 
    mutate(Layer= case_when(
    between(dist_surf,-500,-20) ~ 'out',
    between(dist_surf,-20,500) ~ 'L2/3',
    between(dist_surf,500,1210) ~ 'L5',
    .default = "WTF")) %>% 
      mutate(depthcat = case_when(
      between(dist_surf,-500,-20) ~ 'out',
      between(dist_surf,-20,300) ~ '0-33',
      between(dist_surf,300,600) ~ '300-600',
      between(dist_surf,600,900) ~ '600-900',
      between(dist_surf,900,1220) ~ '900-1200',
      .default = "WTF"
    ))
```


```{r}

ord <- Layerd %>% filter(phase=='cortex') %>% filter(between(dist_surf,-50,1210))  %>% distinct(cluster_id2, dist_surf) %>%   arrange(dist_surf)  %>% mutate(cluster_id2 = as.factor(cluster_id2)) %>% pull(cluster_id2)
  
  
  
  
  
  # z score and filter
  g1 <-  Layerd %>% filter(phase=='cortex') %>% filter(between(dist_surf,-50,1210)) %>% filter(between(rel_time,-1,1)) %>% select(Behv,cluster_id2,Zscore,rel_time,newgroup)
  

  
  #apply order 
  g1$cluster_id2 <- factor(g1$cluster_id2, levels = ord)
  
  
  #heatmap
  map <-g1 %>% ggplot(aes(rel_time,cluster_id2,fill=Zscore))+
    geom_tile()+
    geom_vline(xintercept = 0, col ='grey',linetype = 'dashed')+
    facet_grid(newgroup~Behv,scales = 'free')+
    scale_fill_gradient2(low = 'darkblue', mid = 'beige', high = 'red', midpoint = 0, limits = c(round(min(g1$Zscore)), round(max(g1$Zscore)*0.5)), breaks = c(round(min(g1$Zscore)),  round(max(g1$Zscore)*0.5)) ,na.value = "darkred")+
    theme_void()+
    theme(plot.margin = unit(c(0,0.2,0,1), 'lines'),
          strip.text.x = element_text(size = 30))+
    labs(fill='Z- scored FR') 
  
   #activity across all units
  smo <- g1 %>% group_by(Behv,rel_time,newgroup) %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4,fill = 'black')+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    facet_grid(newgroup~Behv)+
    theme_minimal()+
    theme(plot.margin = unit(c(0.1,0.2,0,1), 'lines'),
          strip.background = element_blank(),
          strip.text.x = element_blank(),
          axis.text=element_text(size=12),
          axis.title=element_text(size=20,face="bold"))+
    xlab("time from stimulus")+
    ylab("Z-scored FR")
  
  # arrange plots
  plot <- ggpubr::ggarrange(map, smo, heights = c(2, 0.8),vjust= c(0.5,0.5),
                    ncol = 1, nrow = 2, align = "v",common.legend=T,legend = 'right')
  plot
  
g2 <- Layerd%>% filter(phase=='cortex')  %>% filter(Behv =='Opto_Air') %>% filter(between(dist_surf,-50,1210)) %>% filter(between(rel_time,-1,1)) %>% select(Layer,Layer_fine,cluster_id2,Zscore,rel_time,newgroup)
txtx =  g2  %>% distinct(cluster_id2, Layer, newgroup) %>% group_by(Layer,newgroup) %>% count()
   g2 %>% group_by(Layer,rel_time,newgroup) %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4,fill = 'black')+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    facet_grid(Layer~newgroup)+
    theme_minimal()+
     geom_text(data=txtx, aes(x=1.8, y=5, label=n), 
            colour="black", inherit.aes=FALSE, parse=FALSE)
   
   
   g2 <- Layerd%>% filter(phase=='cortex')  %>% filter(Behv =='Opto_Air') %>% filter(between(dist_surf,-20,1210)) %>% filter(between(rel_time,-1,1)) %>% select(Layer,Layer_fine,depthcat,cluster_id2,Zscore,rel_time,newgroup)
txtx =  g2  %>% distinct(cluster_id2, depthcat, newgroup) %>% group_by(depthcat,newgroup) %>% count()
   g2 %>% group_by(depthcat,rel_time,newgroup) %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4,fill = 'black')+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    facet_grid(depthcat~newgroup)+
    theme_minimal()+
     geom_text(data=txtx, aes(x=1.8, y=5, label=n), 
            colour="black", inherit.aes=FALSE, parse=FALSE)
```

# for thalamus
```{r}
ord <- Layerd %>% filter(phase=='Thalamus') %>% filter(between(dist_surf,-50,1210))  %>% distinct(cluster_id2, dist_surf) %>%   arrange(dist_surf)  %>% mutate(cluster_id2 = as.factor(cluster_id2)) %>% pull(cluster_id2)
  
  
  
  
  
  # z score and filter
  g1 <-  Layerd %>% filter(phase=='Thalamus') %>% filter(between(dist_surf,-50,1210)) %>% filter(between(rel_time,-1,1)) %>% select(Behv,cluster_id2,Zscore,rel_time,newgroup)
  

  
  #apply order 
  g1$cluster_id2 <- factor(g1$cluster_id2, levels = ord)
  
  
  #heatmap
  map <-g1 %>% ggplot(aes(rel_time,cluster_id2,fill=Zscore))+
    geom_tile()+
    geom_vline(xintercept = 0, col ='grey',linetype = 'dashed')+
    facet_grid(newgroup~Behv,scales = 'free')+
    scale_fill_gradient2(low = 'darkblue', mid = 'beige', high = 'red', midpoint = 0, limits = c(round(min(g1$Zscore)), round(max(g1$Zscore)*0.5)), breaks = c(round(min(g1$Zscore)),  round(max(g1$Zscore)*0.5)) ,na.value = "darkred")+
    theme_void()+
    theme(plot.margin = unit(c(0,0.2,0,1), 'lines'),
          strip.text.x = element_text(size = 30))+
    labs(fill='Z- scored FR') 
  
   #activity across all units
  smo <- g1 %>% group_by(Behv,rel_time,newgroup) %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4,fill = 'black')+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    facet_grid(newgroup~Behv)+
    theme_minimal()+
    theme(plot.margin = unit(c(0.1,0.2,0,1), 'lines'),
          strip.background = element_blank(),
          strip.text.x = element_blank(),
          axis.text=element_text(size=12),
          axis.title=element_text(size=20,face="bold"))+
    xlab("time from stimulus")+
    ylab("Z-scored FR")
  
  # arrange plots
  plot <- ggpubr::ggarrange(map, smo, heights = c(2, 0.8),vjust= c(0.5,0.5),
                    ncol = 1, nrow = 2, align = "v",common.legend=T,legend = 'right')
  plot
  
g2 <- Layerd%>% filter(phase=='Thalamus')  %>% filter(Behv =='Opto_Air') %>% filter(between(dist_surf,-50,1210)) %>% filter(between(rel_time,-1,1)) %>% select(Layer,Layer_fine,cluster_id2,Zscore,rel_time,newgroup)
txtx =  g2  %>% distinct(cluster_id2, Layer, newgroup) %>% group_by(Layer,newgroup) %>% count()
   g2 %>% group_by(Layer,rel_time,newgroup) %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4,fill = 'black')+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    facet_grid(Layer~newgroup)+
    theme_minimal()+
     geom_text(data=txtx, aes(x=1.8, y=5, label=n), 
            colour="black", inherit.aes=FALSE, parse=FALSE)
   
    g2 <- Layerd%>% filter(phase=='Thalamus')  %>% filter(Behv =='Opto_Air') %>% filter(between(dist_surf,-20,1210)) %>% filter(between(rel_time,-1,1)) %>% select(Layer,Layer_fine,depthcat,cluster_id2,Zscore,rel_time,newgroup)
txtx =  g2  %>% distinct(cluster_id2, depthcat, newgroup) %>% group_by(depthcat,newgroup) %>% count()
   g2 %>% group_by(depthcat,rel_time,newgroup) %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4,fill = 'black')+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    facet_grid(depthcat~newgroup)+
    theme_minimal()+
     geom_text(data=txtx, aes(x=1.8, y=5, label=n), 
            colour="black", inherit.aes=FALSE, parse=FALSE)
```


# actal Opto plot
```{r}
 ord <- Trialless %>% filter(phase=='cortex')  %>% filter(between(rel_time,0,0.1)) %>% group_by(cluster_id2)  %>%
      filter(Behv == 'Airpuff') %>% group_by(cluster_id2) %>%
      summarise(ord = mean(Zscore)) %>%   arrange( ord)  %>% mutate(cluster_id2 = as.factor(cluster_id2)) %>% pull(cluster_id2)
  
  
  
  
  
  # z score and filter
  g1 <-  Trialless  %>% filter(between(rel_time,-1,1)) %>% select(phase,Behv,cluster_id2,Zscore,rel_time,newgroup)
  g1 <- g1 %>% group_by(phase) %>% complete(Behv,nesting(cluster_id2, rel_time), fill = list(Zscore = 0.1)) %>% filter(phase != 'NA')
  g1 <- g1 %>% mutate(Behv = case_when(
    Behv == 'just_opto' ~ 'Opto_only',
    Behv == 'Opto_Air' ~'Airpuff + Opto',
    Behv == 'Airpuff' ~ 'Airpuff',
    .default = 'WTF'
  ))

  g1$cluster_id2 <- factor(g1$cluster_id2, levels = ord)
  
  
  #heatmap
  map <-g1 %>% ggplot(aes(rel_time,cluster_id2,fill=Zscore))+
    geom_tile()+
    geom_vline(xintercept = 0, col ='grey',linetype = 'dashed')+
    facet_grid(phase~Behv,scales = 'free',space='free')+
    scale_fill_gradient2(low = 'darkblue', mid = 'beige', high = 'red', midpoint = 0, limits = c(round(min(g1$Zscore)), round(max(g1$Zscore)*0.5)), breaks = c(round(min(g1$Zscore)),  round(max(g1$Zscore)*0.5)) ,na.value = "darkred")+
    theme_void()+
    theme(plot.margin = unit(c(0,0.2,0,1), 'lines'),
          strip.text.x = element_text(size = 30),
          strip.text.y = element_text(size = 30,angle = 270,margin = margin(r = 8)))+
     guides(fill = guide_colorbar(barheight = 10, barwidth = 2, ticks = FALSE)) 
    labs(fill='Z- scored FR') 
  
   #activity across all units
  smo <- g1 %>% group_by(Behv,rel_time,phase) %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4,fill = 'black')+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    facet_grid(phase~Behv)+
    theme_minimal()+
    theme(plot.margin = unit(c(0.1,0.2,0,1), 'lines'),
          strip.background = element_blank(),
          strip.text.x = element_blank(),
          axis.text=element_text(size=12),
          axis.title=element_text(size=20,face="bold"),
           strip.text.y = element_text(size = 20,angle = 270,margin = margin(r = 8)))+
    xlab("time from stimulus")+
    ylab("Z-scored FR")
  
  plot <- ggpubr::ggarrange(map, smo, heights = c(2, 0.8),vjust= c(0.5,0.5),
                    ncol = 1, nrow = 2, align = "v",common.legend=T,legend = 'right')
  plot
  
  library(export)
x11() # open graphics window
# now maximize this window so it is full screen


print(plot)
graph2tif(x= plot, file='C:/Users/Freitag/Desktop/Opto_overview',
         width = dev.size(units="px")[[1]]/90,
         height = dev.size(units="px")[[2]]/90,
         dpi = 900)

dev.off()

```

# Opto stats
```{r}

Trialless <- Trialless %>% left_join(Trialless %>% filter(rel_time < 0) %>% group_by(Behv,newgroup) %>% summarise(bl = mean(Zscore))) %>% ungroup %>% mutate(Zscore = Zscore - bl)

Test4_org <- Trialless  %>%  distinct(phase,rel_time,Behv,Zscore, cluster_id2,id)%>% filter(between(rel_time,0,0.04))  %>%  group_by(phase,cluster_id2,Behv) %>% slice_max(Zscore) %>% distinct(phase,Behv,cluster_id2,id,Zscore) %>% separate_wider_delim(id, names = c('Mouse','Session'), delim = '_') %>% ungroup %>% na.omit()

Test4 <- Test4_org %>%  mutate(Zscore = Zscore - min(Zscore) +1) %>% mutate(across(c(phase,Behv,Mouse,Session), as.factor))

mod3 <-lme4::glmer(data= Test4, Zscore ~ Behv + phase + Behv*phase + (1 |Mouse) + (1 | Mouse:Session), family =  Gamma(link='inverse'))
mod0 <-lme4::glmer(data= Test4, Zscore ~ 1 + (1 |Mouse) + (1 | Mouse:Session), family =  Gamma(link='inverse'))

anova(mod3,mod0)




library(emmeans)

emmeans::emmeans(mod3, pairwise ~ newgroup)

# layer conditional
emmeans(mod3, pairwise ~phase| Behv)
emmeans(mod3, pairwise ~Behv| phase)
laycon




emmeans_Behv_simp <- emmeans::emmeans(mod3, ~ newgroup , type = "response")
behvcon_simp <- emmeans::emmeans(mod3, pairwise ~ newgroup)
# Convert to tibble
pdata <- emmeans_Behv_simp %>% as_tibble() %>% mutate(newgroup = as.character(newgroup))
pdata <- pdata %>% mutate(newgroup = trimws(as.character(newgroup)))

# Prepare p-values
pvals <- behvcon_simp$contrasts %>%
  as_tibble() %>%
  separate_wider_delim(contrast, names = c("group1", "group2"), delim = "-") %>%
  mutate(psig = case_when(
    p.value < 0.001 ~'***',
    p.value < 0.01 ~'**',
    p.value < 0.05 ~'*',
     p.value > 0.05  ~'NS',
  )) %>%
  mutate(group1 = as.character(group1), group2 = as.character(group2))  %>% mutate(group1 = trimws(group1), group2 = trimws(group2)) %>%  # Ensure character type
  left_join(pdata %>% mutate(newgroup = as.character(newgroup)), 
            by = join_by(group1 == newgroup))

# Plot
 ggplot(pdata %>% mutate(response = response + min(Test4_org$Zscore)-1, asymp.LCL = asymp.LCL  + min(Test4_org$Zscore)-1, asymp.UCL = asymp.UCL  + min(Test4_org$Zscore)-1) %>% mutate(newgroup = case_when(
    newgroup=='FS'~'FS',
    newgroup=='good'~'regular',
    newgroup=='mua'~'inverted',
    .default = 'Fuck')) %>% mutate(newgroup= factor(newgroup, levels=c("FS", "regular", "inverted"))), aes(x = newgroup, y = response)) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.2) +
  geom_point()+
  geom_text(aes(label = round(response, 2)), hjust = -1) +
  theme_minimal()+
  ylab('max Zscore response')+
  ggpubr::stat_pvalue_manual(pvals %>% mutate(response = response + min(Test4_org$Zscore)-1, asymp.LCL = asymp.LCL  + min(Test4_org$Zscore)-1, asymp.UCL = asymp.UCL  + min(Test4_org$Zscore)-1)  %>% mutate(group1 = case_when(
    group1=='FS'~'FS',
    group1=='good'~'regular',
    group1=='mua'~'inverted',
    .default = 'Fuck')) %>% mutate(group2 = case_when(
    group2=='FS'~'FS',
    group2=='good'~'regular',
    group2=='mua'~'inverted',
    .default = 'Fuck')) %>%  mutate(y.position = asymp.UCL + 0.2, y.position = ifelse(group1=='FS' & group2=='inverted', y.position+0.2,y.position)), label = "psig", 
                             xmin = "group1", xmax = "group2", y.position = "y.position")+
  coord_fixed(ratio=0.4)
ggsave('C:/users/Freitag/Desktop/waveform_stats.tiff', bg= 'white',dpi=900)


 

boxdata <- Test4_org  %>% group_by(newgroup) %>%
  summarise(min = max(quantile(Zscore, probs = 0),quantile(Zscore, probs = 0.25)*1.5),
            lower = quantile(Zscore, probs = 0.25),
            median = quantile(Zscore, probs = 0.5),
            mean = mean(Zscore),
            higher = quantile(Zscore, probs = 0.75),
            max = min(quantile(Zscore, probs = 1),quantile(Zscore, probs = 0.75)*1.5))

ggplot(boxdata, aes(x=newgroup, ymin = min, lower = lower, middle = mean, upper = higher, ymax = max)) +
  geom_boxplot(stat = "identity")+
  theme_minimal()+
   ggpubr::stat_pvalue_manual(pvals  %>% mutate(y.position = boxdata$max + 0.5, y.position = ifelse(group1=='FS' & group2=='mua', y.position+1,y.position)) %>% select(group1,group2,psig,y.position) %>% bind_cols(boxdata), label = "psig", 
                             xmin = "group1", xmax = "group2", y.position = "y.position")
  coord_fixed(ratio=0.5)

```

