---
title: "Master"
output:
  html_document: default
  pdf_document: default
date: "2024-09-25"
editor_options: 
  chunk_output_type: inline
---

```{r, include=FALSE}
knitr::opts_chunk$set()
```

#load packages
```{r}
library(tidyverse)
source("C:/Users/Freitag/Documents/GitHub/Master_thesis/Analysis/Analysis/Master_helper.R")
```

# load data
```{r}
#Data <- data.table::fread("D:/Florian_paper/Florian/Aligned_Data/Analysable_data/wrangled_Data/R_outputs/final_combined_data.csv", showProgress = T)
#combcont <- data.table::fread("E:/Florian_paper/Florian/Aligned_Data/Analysable_data/wrangled_Data/R_outputs/combcont.csv",showProgress=T)
Trialless <- read_csv("E:/Florian_paper/Florian/Aligned_Data/Analysable_data/wrangled_Data/R_outputs/Trialless.csv")

# Zeta <- read_csv("C:/Users/deepl/Desktop/com_Data/wrangled_Data/Unit_Behv.csv")


```

# overview plots
```{r}
Plot_overview(Trialless, orderby_Behv = "A2L", by_time = F, theme_smo = theme_minimal())
#ggsave('C:/users/Freitag/Desktop/Overview.tiff', bg= 'white',dpi=900)
Plot_overview(Trialless, orderby_Behv = "A2L", by_time = T, theme_smo = theme_minimal())
#ggsave("E:/Florian/Aligned_Data/Analysable_data/figures//overview_byTime.tiff", bg = "white")




plot_overview_perID(Trialless, orderby_Behv = "A2L", save = "E:/Florian/Aligned_Data/Analysable_data/figures/sessions")


Plot_overview2 <- function(Trialless,orderby_Behv = 'A2L',by_time = F,theme_smo = theme_minimal()) {
  if(by_time ==F) {
    ord <- Trialless  %>% filter(between(rel_time,0,0.1)) %>% group_by(cluster_id2)  %>%
      filter(Behv == orderby_Behv) %>% group_by(cluster_id2) %>%
      summarise(ord = mean(Zscore)) %>%   arrange( ord)  %>% mutate(cluster_id2 = as.factor(cluster_id2)) %>% pull(cluster_id2)
  }
  if(by_time ==T){
    ord <-  Trialless %>% group_by(cluster_id2)  %>%
      filter(between(rel_time,-1,1)) %>%  filter(Behv == orderby_Behv ) %>% group_by(cluster_id2) %>% 
      slice_max(Zscore,n=1,with_ties=F) %>% summarise(ord = rel_time) %>%   arrange( ord)  %>% distinct() %>% 
      mutate(cluster_id2 = as.factor(cluster_id2)) %>% pull(cluster_id2)
  }
  
  
  
  
  
  # z score and filter
  g1 <- Trialless  %>% filter(between(rel_time,-1,1)) %>% select(Behv,cluster_id2,Zscore,rel_time)
  

  
  #apply order 
  g1$cluster_id2 <- factor(g1$cluster_id2, levels = ord)
  
  
  #heatmap
  map <-g1 %>% mutate(Zscore= ifelse(Zscore > 8,8,Zscore)) %>%  ggplot(aes(rel_time,cluster_id2,fill=Zscore))+
    geom_tile()+
    geom_vline(xintercept = 0, col ='grey',linetype = 'dashed')+
    facet_wrap(~Behv,scales = 'free')+
    scale_fill_gradientn(colors = c("darkblue",'beige' ,"beige", "red"),
                       values = scales::rescale(c(min(g1$Zscore), -0.65, 0, 8)),
                       guide = guide_colorbar(
                         ticks = FALSE,  # Remove intermediate ticks
                        draw.ulim = FALSE,     # Remove top tick
                         draw.llim = FALSE,   
                        
                       ),
                       breaks = c(-2, 8))+
    theme_void()+
    theme(plot.margin = unit(c(0,0.2,0,1), 'lines'),
          strip.text.x = element_text(size = 30))+
    labs(fill='Z- scored FR') 
  
  
  #activity across all units
  smo <- g1 %>% group_by(Behv,rel_time) %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% ggplot(aes(rel_time,rate3))+
    geom_line()+
    geom_ribbon(aes(ymin = rate3-se, ymax = rate3+se),alpha = 0.4,fill = 'black')+
    geom_vline(xintercept = 0, col ='darkgrey',linetype = 'dashed')+
    facet_wrap(~Behv)+
    theme_smo+
    theme(plot.margin = unit(c(0.1,0.2,0,1), 'lines'),
          strip.background = element_blank(),
          strip.text.x = element_blank(),
          axis.text=element_text(size=12),
          axis.title=element_text(size=20))+
    xlab("time from stimulus")+
    ylab("Z-scored FR")
  
  # arrange plots
  plot <- ggpubr::ggarrange(map, smo, heights = c(2, 0.8),vjust= c(0.5,0.5),
                    ncol = 1, nrow = 2, align = "v",common.legend=T,legend = 'right')
  plot
  
}

Plot_overview2(Trialless %>% left_join(Trialless %>% filter(rel_time < 0) %>% group_by(Behv) %>% summarise(bl = mean(Zscore))) %>% ungroup %>% mutate(Zscore = Zscore - bl), orderby_Behv = "A2L", by_time = F, theme_smo = theme_minimal())
ggsave('C:/users/Freitag/Desktop/Overview_v2.tiff', bg= 'white',dpi=900)


Trialless %>% group_by(Behv,rel_time) %>% summarise( rate3 = mean(Zscore))  %>%  filter(between(rel_time,0,0.04))  %>% group_by(Behv) %>% summarise(max= max(rate3), sd = sd(rate3), sem = sd/sqrt(n())) %>% mutate(norm_to_A2L = max / (max(max)), perc_change = -(1-norm_to_A2L) *100)


Trialless %>% filter(between(rel_time,0,0.04))  %>% group_by(cluster_id2,Behv) %>% slice_max(Zscore) %>% group_by(Behv) %>% summarise(max = mean(Zscore), sd = sd(Zscore))

 Trialless2 <- combcont %>% group_by(Behv,rel_time, cluster_id2)  %>% 
  mutate(rate = (sum(event_count)/n_trials), rate = rate/0.01) %>% ungroup() %>% 
  distinct(Behv,rel_time,cluster_id2,rate,depth,n_spikes,id) %>% group_by(Behv,cluster_id2) %>% 
  mutate(sd = sd(rate), Zscore = (rate - mean(rate))/sd(rate))
 
Trialless2 %>% filter(between(rel_time,0,0.04))  %>% group_by(Behv,cluster_id2) %>% summarise(max = mean(Zscore), sd = mean(sd)) %>% summarise(sd= mean(sd))

unitless <- combcont %>% group_by(Behv,rel_time, Trial2)  %>% 
  mutate(rate = (sum(event_count)/n_trials), rate = rate/0.01) %>% ungroup() %>% 
  distinct(Behv,rel_time,Trial2,rate,depth,n_spikes,id) %>% group_by(Behv,Trial2) %>% 
  mutate(sd = sd(rate), Zscore = (rate - mean(rate))/sd(rate))

unitless %>% filter(between(rel_time,0,0.04))  %>% group_by(Trial2,Behv) %>% summarise(Zscore = mean(Zscore)) %>% group_by(Behv) %>% summarise(max = mean(Zscore), sd = sd(Zscore))

combcont %>% select(cluster_id2,Trial2,rel_time,event_count,Behv,n_trials)


Trialless %>%
  group_by(Behv, rel_time) %>%
  summarise(
    rate3 = mean(Zscore),    # Mean Z-scored firing rate
    SD_Z = sd(Zscore)        # Standard deviation of Z-scored firing rate
  ) %>%
  filter(between(rel_time, 0, 0.04)) %>%
  group_by(Behv) %>%
  summarise(
    max_rate = max(rate3),   # Maximum mean Z-score in time window
    max_SD = mean(SD_Z)       # Maximum SD in time window
  )


Trialless %>% filter(between(rel_time,0,0.04)) %>% filter(between(Zscore,-3,5)) %>% group_by(Behv,rel_time) %>% summarise( rate3 = mean(Zscore), sd = sd(Zscore), se = sd/sqrt(n())) %>% slice_max(rate3)

Trialless %>% filter(between(rel_time,0,0.04))  %>% group_by(Behv,rel_time) %>% summarise( rate3 = mean(Zscore), IQR =  IQR(Zscore),MAD_Z <- median(abs(Zscore - median(Zscore)))) %>% slice_max(rate3)
 IQR(Trialless$Zscore)
sd(c(1,2,3,1,2,3,1,2,3,400))


Trialless %>% filter(between(rel_time,0,0.04)) %>% ggplot(aes(Zscore,fill=Behv))+
  geom_histogram()
```

# Layer plots
```{r}
Layerd <- add_layers(Trialless, depthpath = "E:/Florian_paper/Florian/Aligned_Data/Analysable_data/depths")


Layerd %>%
  filter(Layer %in% c("L2/3", "L5")) %>%
  filter(between(rel_time, -1, 1)) %>%
  group_by(Layer, Behv, rel_time) %>%
  summarise(rate3 = mean(Zscore), sd = sd(Zscore), se = sd / sqrt(n())) %>%
  ggplot(aes(rel_time, rate3)) +
  geom_line() +
  geom_ribbon(aes(ymin = rate3 - se, ymax = rate3 + se), alpha = 0.4, fill = "black") +
  geom_vline(xintercept = 0, col = "sienna2", linetype = "dashed") +
  facet_grid(Layer ~ Behv) +
  theme_minimal() +
  xlab("time from stimulus") +
  ylab("Z-scored FR")+ 
  theme(strip.text = element_text(size = 30),
         axis.title=element_text(size=20),axis.text=element_text(size=12))+coord_fixed(ratio=0.5)
ggsave('C:/users/Freitag/Desktop/LayerOV_V2.tiff', bg= 'white',dpi=900)



Layerd %>%
  filter(Layer_fine %in% c("L1", "L2/3", "L5A", "L5B", "L6")) %>%
  filter(between(rel_time, -1, 1)) %>%
  group_by(Layer_fine, Behv, rel_time) %>%
  summarise(rate3 = mean(Zscore), sd = sd(Zscore), se = sd / sqrt(n())) %>%
  ggplot(aes(rel_time, rate3)) +
  geom_line() +
  geom_ribbon(aes(ymin = rate3 - se, ymax = rate3 + se), alpha = 0.4, fill = "black") +
  geom_vline(xintercept = 0, col = "sienna2", linetype = "dashed") +
  facet_grid(Layer_fine ~ Behv) +
  theme_minimal() +
  xlab("time from stimulus") +
  ylab("Z-scored FR")
#ggsave("E:/Florian/Aligned_Data/Analysable_data/figures/Layers_fine.tiff", bg = "white")

Layerd %>%
  mutate(Zscore = Zscore + case_when(
    Layer_fine == "L1" ~ 8,
    Layer_fine == "L2/3" ~ 6,
    Layer_fine == "L5A" ~ 4,
    Layer_fine == "L5B" ~ 2,
    Layer_fine == "L6" ~ 0
  )) %>%
  ungroup() %>%
  filter(Layer_fine %in% c("L1", "L2/3", "L5A", "L5B", "L6")) %>%
  filter(between(rel_time, -1, 1)) %>%
  group_by(Layer_fine, Behv, rel_time) %>%
  summarise(rate3 = mean(Zscore), sd = sd(Zscore), se = sd / sqrt(n())) %>%
  ggplot(aes(rel_time, rate3, col = Layer_fine)) +
  geom_line() +
  geom_ribbon(aes(ymin = rate3 - se, ymax = rate3 + se), alpha = 0.4, fill = "black") +
  geom_vline(xintercept = 0, col = "sienna2", linetype = "dashed") +
  facet_wrap(~Behv) +
  theme_minimal() +
  xlab("time from stimulus") +
  ylab("Z-scored FR")
#ggsave("E:/Florian/Aligned_Data/Analysable_data/figures/Layers_fine_butdifferent.tiff", bg = "white")



labels <- Layerd %>%
  distinct(cluster_id2, Layer_fine, dist_surf) %>%
  filter(Layer_fine != "WTF") %>%
  group_by(Layer_fine) %>%
  summarise(
    n = n(),
    x = (min(dist_surf) + max(dist_surf)) / 2
  ) %>%
  mutate(y = 5)
Layerd %>%
  distinct(cluster_id2, Layer_fine, dist_surf) %>%
  filter(Layer_fine != "WTF") %>%
  ggplot() +
  geom_histogram(aes(dist_surf, fill = Layer_fine), binwidth = 20) +
  geom_text(data = labels, aes(x, y, label = n))



Layerd  %>% filter(Layer %in% c("L2/3", "L5")) %>% group_by(Behv,rel_time,Layer) %>% summarise( rate3 = mean(Zscore))  %>%  filter(between(rel_time,0,0.04))  %>% group_by(Behv,Layer) %>% summarise(max= max(rate3)) %>% mutate(norm_to_L5 = max / (max(max)), perc_change = -(1-norm_to_L5) *100)

#ggsave("E:/Florian/Aligned_Data/Analysable_data/figures/what_are_layers.tiff", bg = "white")
```



#PC plots
```{r}
PCdat <- Zeta %>%
  distinct(unit, Behv_combined2) %>%
  right_join(Trialless, by = join_by("unit" == "cluster_id2"))

PCdat %>%
  filter(between(rel_time, -1, 1)) %>%
  filter(Behv != "W2T") %>%
  na.omit() %>%
  group_by(Behv, rel_time, Behv_combined2) %>%
  summarise(rate3 = mean(Zscore), sd = sd(Zscore), se = sd / sqrt(n())) %>%
  ggplot(aes(rel_time, rate3, col = Behv_combined2)) +
  geom_smooth(span = 0.08) +
  facet_grid(~Behv)

PCdat %>%
  filter(between(rel_time, -1, 1)) %>%
  filter(Behv != "W2T") %>%
  na.omit() %>%
  mutate(Behv_combined2 = ifelse(Behv_combined2 == "PC", "PC", "A2L")) %>%
  group_by(Behv, rel_time, Behv_combined2) %>%
  summarise(rate3 = mean(Zscore), sd = sd(Zscore), se = sd / sqrt(n())) %>%
  ggplot(aes(rel_time, rate3, col = Behv_combined2)) +
  geom_smooth(span = 0.08) +
  geom_line() +
  facet_grid(~Behv)

PC_filter <- Zeta %>%
  filter(Behv_combined2 == "PC") %>%
  pull(unit)
Trialless %>%
  filter(cluster_id2 %in% PC_filter) %>%
  filter(between(rel_time, -0.1, 0.6)) %>%
  group_by(Behv, rel_time) %>%
  summarise(rate3 = mean(Zscore), sd = sd(Zscore), se = sd / sqrt(n())) %>%
  ggplot(aes(rel_time, rate3)) +
  geom_smooth(span = 0.1) +
  geom_vline(xintercept = 0, col = "sienna2", linetype = "dashed") +
  geom_vline(xintercept = 0.25, col = "sienna2", linetype = "dashed") +
  facet_wrap(~Behv) +
  theme_minimal()
```


# whsiking
```{r, include=FALSE}
whisk <- Zeta %>%
  distinct(unit, Behv_combined) %>%
  right_join(Trialless, by = join_by("unit" == "cluster_id2"))

whisk %>%
  filter(!str_detect(Behv_combined, "Whisk")) %>%
  distinct(Behv_combined)

whisk %>%
  filter(str_detect(Behv_combined, "Whisk")) %>%
  filter(Behv == "W2T") %>%
  filter(between(rel_time, -1, 1)) %>%
  group_by(rel_time) %>%
  summarise(rate3 = mean(Zscore), sd = sd(Zscore), se = sd / sqrt(n())) %>%
  ggplot(aes(rel_time, rate3)) +
  geom_smooth(span = 0.08) +
  geom_line()

whisk %>%
  filter(!str_detect(Behv_combined, "Whisk")) %>%
  filter(Behv == "W2T") %>%
  filter(between(rel_time, -1, 1)) %>%
  group_by(rel_time) %>%
  summarise(rate3 = mean(Zscore), sd = sd(Zscore), se = sd / sqrt(n())) %>%
  ggplot(aes(rel_time, rate3)) +
  geom_smooth(span = 0.08) +
  geom_line()


Trialless %>%
  filter(between(rel_time, -1, 1)) %>%
  select(Behv, cluster_id2, Zscore, rel_time) %>%
  filter(Behv == "W2T") %>%
  group_by(rel_time) %>%
  summarise(rate3 = mean(Zscore), sd = sd(Zscore), se = sd / sqrt(n())) %>%
  ggplot(aes(rel_time, rate3)) +
  geom_line() +
  geom_smooth(span = 0.08)
```

# misc plots
```{r}
Trialless %>%
  separate_wider_delim(cluster_id2, delim = "_", names = c("del", "Mouse", "Day"), cols_remove = F) %>%
  unite("id", c(Mouse, Day)) %>%
  select(!del) %>%
  group_by(id) %>%
  summarise(n = n_distinct(cluster_id2)) %>%
  arrange(-n) %>%
  ggplot(aes(reorder(id, -n), n)) +
  geom_col() +
  scale_x_discrete(guide = guide_axis(angle = 45)) +
  theme_minimal() +
  ggtitle("neurons per session")
```

# single unit plots
```{r}
combcont <- data.table::fread("E:/Florian_paper/Florian/Aligned_Data/Analysable_data/wrangled_Data/R_outputs/combcont.csv",showProgress=T)
L2 <- add_layers(combcont %>% filter(between(rel_time,-1,1)), depthpath = "D:/Florian_paper/Florian/Aligned_Data/Analysable_data/depths")
su <-L2 %>% filter(cluster_id2 %in% c('78_M2_3','50_M6_3','44_M2_1'))



plot_single_unit2(su,'78_M2_3',0.1)
ggsave('C:/users/Freitag/Desktop/78_M2_3_ds850.tiff', bg= 'white',dpi=900)

plot_single_unit2(su,'44_M2_1',0.1)
ggsave('C:/users/Freitag/Desktop/44_M2_1_ds270.tiff', bg= 'white',dpi=900)

plot_single_unit2(su,'50_M6_3',smoothness = 0.1)
ggsave('C:/users/Freitag/Desktop/50_M6_3_ds770.tiff', bg= 'white',dpi=900)
```






# stats for Trialless with depth
```{r}
library(emmeans)

Trialless <- add_layers(Trialless,"E:/Florian_paper/Florian/Aligned_Data/Analysable_data/depths" )
Trialless <- Trialless %>% left_join(Trialless %>% filter(rel_time < 0) %>% group_by(Behv,Layer) %>% summarise(bl = mean(Zscore))) %>% ungroup %>% mutate(Zscore = Zscore - bl)

# for backtransforming later
Test4_org <- Trialless  %>%  distinct(Layer,rel_time,Behv,Zscore, cluster_id2,id)%>% filter(between(rel_time,0,0.04)) %>%  filter(Layer %in% c('L2/3','L5')) %>%  group_by(Layer,cluster_id2,Behv) %>% slice_max(Zscore) %>% distinct(Layer,Behv,cluster_id2,id,Zscore) %>% separate_wider_delim(id, names = c('Mouse','Session'), delim = '_') %>% ungroup %>% na.omit()

# make all values positive to use Beta distribution
Test4 <- Test4_org %>%  mutate(Zscore = Zscore - min(Zscore) +1) %>% mutate(across(c(Layer,Behv,Mouse,Session), as.factor))


# fit and test the model
mod3 <-lme4::glmer(data= Test4, Zscore ~ Behv + Layer + Behv*Layer + (1 |Mouse) + (1 | Mouse:Session), family =  Gamma(link='inverse'))
summary(mod3, type= 'response')
mod0 <-lme4::glmer(data= Test4, Zscore ~ 1 + (1 |Mouse) + (1 | Mouse:Session), family =  Gamma(link='inverse'))


se_effects <- sqrt(diag(vcov(mod3)))  # Standard errors in inverse scale
original_scale_sd <- se_effects * (original_scale_means^2)
summary(mod3)
anova(mod3,mod0)


res <- DHARMa::simulateResiduals(fittedModel = mod3, plot = T,refit=F,use.u = T)
DHARMa::plotQQunif(res, testUniformity = F,testOutliers = F,testDispersion = F)


#Post hoc
# do test on model scale
library(emmeans)
#overall Behv
g <- emmeans(mod3, pairwise ~ Behv,type='response')$contrast %>% as_tibble()


# Behv conditional 
emmeans(mod3, pairwise ~ Behv| Layer)

# overall Layer
emmeans::emmeans(mod3, pairwise ~ Layer)
t <-  emmeans(mod3, pairwise ~ Layer,type='response')$contrast %>% as_tibble()
# layer conditional
emmeans(mod3, pairwise ~Layer| Behv)
t2 <-  emmeans(mod3, pairwise ~ Layer|Behv,type='response')$contrast %>% as_tibble()

# for values, response scale


?emmeans





pvals
pdata


emmeans_Layer <- emmeans::emmeans(mod3, ~ Layer| Behv, type = "response")


emmeans_Layer %>% as_tibble() %>% ggplot(aes(Layer,response))+
  geom_errorbar(aes(ymin= asymp.LCL, ymax = asymp.UCL))+
  facet_wrap(~Behv)+
  geom_point()+
  geom_text(aes(label = round(response,2)),hjust = -1)+
  theme_minimal()



emmeans_Behv <- emmeans::emmeans(mod3, ~ Behv | Layer, type = "response")

# Convert to tibble
pdata <- emmeans_Behv %>% as_tibble() %>% mutate(Behv = as.character(Behv))
pdata <- pdata %>% mutate(Behv = trimws(as.character(Behv)))

# Prepare p-values
pvals <- behvcon$contrasts %>%
  as_tibble() %>%
  separate_wider_delim(contrast, names = c("group1", "group2"), delim = "-") %>%
  mutate(psig = "***") %>%
  mutate(group1 = as.character(group1), group2 = as.character(group2))  %>% mutate(group1 = trimws(group1), group2 = trimws(group2)) %>%  # Ensure character type
  left_join(pdata %>% mutate(Behv = as.character(Behv)), 
            by = join_by(group1 == Behv,Layer)) %>%  # Join with corrected types
  mutate(y.position = asymp.UCL + 0.5) %>% mutate(y.position = ifelse(group1=='A2L' & group2=='W2T', y.position+0.5,y.position))
# Plot
ggplot(pdata, aes(x = Behv, y = response)) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.2) +
  geom_point()+
  geom_text(aes(label = round(response, 2)), hjust = -1) +
  facet_wrap(~Layer) +
  theme_minimal()+
  ggpubr::stat_pvalue_manual(pvals, label = "psig", 
                             xmin = "group1", xmax = "group2", y.position = "y.position")



emmeans_Behv_simp <- emmeans::emmeans(mod3, ~ Behv , type = "response")
behvcon_simp <- emmeans::emmeans(mod3, pairwise ~ Behv)
# Convert to tibble
pdata <- emmeans_Behv_simp %>% as_tibble() %>% mutate(Behv = as.character(Behv))
pdata <- pdata %>% mutate(Behv = trimws(as.character(Behv)))

# Prepare p-values
pvals <- behvcon_simp$contrasts %>%
  as_tibble() %>%
  separate_wider_delim(contrast, names = c("group1", "group2"), delim = "-") %>%
  mutate(psig = case_when(
    p.value < 0.001 ~'***',
    p.value < 0.01 ~'**',
    p.value < 0.05 ~'*',
     p.value > 0.05  ~'NS',
  )) %>%
  mutate(group1 = as.character(group1), group2 = as.character(group2))  %>% mutate(group1 = trimws(group1), group2 = trimws(group2)) %>%  # Ensure character type
  left_join(pdata %>% mutate(Behv = as.character(Behv)), 
            by = join_by(group1 == Behv)) %>%  # Join with corrected types
  mutate(y.position = asymp.UCL + 0.5) %>% mutate(y.position = ifelse(group1=='A2L' & group2=='W2T', y.position+0.5,y.position))
# Plot
ggplot(pdata, aes(x = Behv, y = response)) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.2) +
  geom_point()+
  geom_text(aes(label = round(response, 2)), hjust = -1) +
  theme_minimal()+
  ylab('max Zscore response')+
  ggpubr::stat_pvalue_manual(pvals, label = "psig", 
                             xmin = "group1", xmax = "group2", y.position = "y.position")
ggsave('C:/Users/Freitag/Desktop/pvals_Behv_simp.tiff', bg='white')



emmeans_Layer_simp <- emmeans::emmeans(mod3, ~ Layer , type = "response")
Layercon_simp <- emmeans::emmeans(mod3, pairwise ~ Layer)
# Convert to tibble
pdata <- emmeans_Layer_simp %>% as_tibble() 
pdata <- pdata %>% mutate(Layer = trimws(as.character(Layer)))

# Prepare p-values
pvals <- Layercon_simp$contrasts %>%
  as_tibble() %>%
  separate_wider_delim(contrast, names = c("group1", "group2"), delim = "-") %>%
  mutate(psig = case_when(
    p.value < 0.001 ~'***',
    p.value < 0.01 ~'**',
    p.value < 0.05 ~'*',
     p.value > 0.05  ~'NS',
  )) %>% mutate( group1 = 'L2/3')%>%
  mutate(group1 = as.character(group1), group2 = as.character(group2))  %>% mutate(group1 = trimws(group1), group2 = trimws(group2)) %>%  # Ensure character type
  left_join(pdata %>% mutate(Layer = as.character(Layer)), 
            by = join_by(group1 ==Layer)) %>%  # Join with corrected types
  mutate(y.position = asymp.UCL + 0.5)
# Plot
ggplot(pdata, aes(x = Layer, y = response)) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.2) +
  geom_point()+
  geom_text(aes(label = round(response, 2)), hjust = -1) +
  theme_minimal()+
  ylab('max Zscore response')+
  ggpubr::stat_pvalue_manual(pvals, label = "psig", 
                             xmin = "group1", xmax = "group2", y.position = "y.position")
ggsave('C:/Users/Freitag/Desktop/pvals_Layer_simp.tiff', bg='white')




Trialless %>% ggplot(aes(Behv, Zscore))+
  geom_boxplot(fatten = NULL)+
  stat_summary(fun.y = mean, geom = "errorbar", aes(ymax = ..y.., ymin = ..y..),
               width = 0.75, size = 1, linetype = "solid")+
  theme_minimal()+ggpubr::stat_pvalue_manual(pvals, label = "psig", 
                             xmin = "group1", xmax = "group2", y.position = "y.position")
 

Trialless %>% filter(between(rel_time,0.01,0.04)) %>% group_by(Behv) %>% summarise(mean(Zscore))

quantile(Trialless$Zscore)

g
t
t2 %>% mutate(p.value = round(p.value,4))


summary(mod3, type= 'response')

emmeans(mod3, pairwise ~ Behv,type='response')

library(equatiomatic)

extract_eq(mod3,show_distribution = TRUE,use_coefs = TRUE)
mod3

broom::glance(mod3)
broom::tidy(mod3)

 
```
# plot for behv stats


$$
\begin{aligned}
  
    \alpha_{j}  &\sim N \left(0, 0.02 \right)
    \text{, for Mouse:Session j = 1,} \dots \text{,J} \\
    \alpha_{k}  &\sim N \left(0, 0.02 \right)
    \text{, for Mouse k = 1,} \dots \text{,K}
\end{aligned}
$$
$$
\begin{aligned}
    Zscore_{ijk} &\sim \text{Gamma}(\lambda_{ijk}) \quad \text{with } \lambda_{ijk} = \frac{1}{\eta_{ijk}} \\ 
    \eta_{ijk} &= \beta_0 + \beta_1 \text{Behv}_i + \beta_2 \text{Layer}_j + \beta_3 (\text{Behv}_i \times \text{Layer}_j) + \alpha_k + \alpha_{jk} \\ 
    \alpha_k &\sim N(0, \sigma^2_{\text{Mouse}}) \\ 
    \alpha_{jk} &\sim N(0, \sigma^2_{\text{Session within Mouse}})
\end{aligned}
$$
$$Zscore_{ijk} \sim \text{Gamma}(\lambda_{ijk}) \quad \text{with } \lambda_{ijk} = \frac{1}{\eta_{ijk}} \quad \\ \eta_{ijk} = \beta_0 + \beta_1 \text{Behv}_i + \beta_2 \text{Layer}_j + \beta_3 (\text{Behv}_i \times \text{Layer}_j) + \alpha_k + \alpha_{jk} \\ \alpha_k \sim N(0, \sigma^2_{\text{Mouse}}) \\ \alpha_{jk} \sim N(0, \sigma^2_{\text{Session within Mouse}})$$

```{r}
emmeans_Behv_simp <- emmeans::emmeans(mod3, ~ Behv , type = "response")
behvcon_simp <- emmeans::emmeans(mod3, pairwise ~ Behv)
# Convert to tibble
pdata <- emmeans_Behv_simp %>% as_tibble() %>% mutate(Behv = as.character(Behv))
pdata <- pdata %>% mutate(Behv = trimws(as.character(Behv)))

# Prepare p-values
pvals <- behvcon_simp$contrasts %>%
  as_tibble() %>%
  separate_wider_delim(contrast, names = c("group1", "group2"), delim = "-") %>%
  mutate(psig = case_when(
    p.value < 0.001 ~'***',
    p.value < 0.01 ~'**',
    p.value < 0.05 ~'*',
     p.value > 0.05  ~'NS',
  )) %>%
  mutate(group1 = as.character(group1), group2 = as.character(group2))  %>% mutate(group1 = trimws(group1), group2 = trimws(group2)) %>%  # Ensure character type
  left_join(pdata %>% mutate(Behv = as.character(Behv)), 
            by = join_by(group1 == Behv))

# Plot
ggplot(pdata %>% mutate(response = response + min(Test4_org$Zscore)-1, asymp.LCL = asymp.LCL  + min(Test4_org$Zscore)-1, asymp.UCL = asymp.UCL  + min(Test4_org$Zscore)-1), aes(x = Behv, y = response)) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.2) +
  geom_point()+
  geom_text(aes(label = round(response, 2)), hjust = -1) +
  theme_minimal()+
  ylab('max Zscore response')+
  ggpubr::stat_pvalue_manual(pvals %>% mutate(response = response + min(Test4_org$Zscore)-1, asymp.LCL = asymp.LCL  + min(Test4_org$Zscore)-1, asymp.UCL = asymp.UCL  + min(Test4_org$Zscore)-1, y.position = asymp.UCL + 0.5) %>% mutate(y.position = ifelse(group1=='A2L' & group2=='W2T', y.position+0.5,y.position)), label = "psig", 
                             xmin = "group1", xmax = "group2", y.position = "y.position")+
  coord_fixed(ratio=1)
#ggsave('C:/users/Freitag/Desktop/Bhev_stats.tiff', bg= 'white',dpi=900)


 

boxdata <- Trialless %>%  filter(between(rel_time,0,0.04)) %>%  filter(Layer %in% c('L2/3','L5')) %>% group_by(Behv) %>%
  summarise(min = quantile(Zscore, probs = 0),
            `25th` = quantile(Zscore, probs = 0.25),
            median = quantile(Zscore, probs = 0.5),
            mean = mean(Zscore),
            `75th` = quantile(Zscore, probs = 0.75),
            max = quantile(Zscore, probs = 1)) %>%  mutate(asymp.LCL = pdata$asymp.LCL  + min(Test4_org$Zscore)-1, asymp.UCL = pdata$asymp.UCL  + min(Test4_org$Zscore)-1)

ggplot(boxdata, aes(x=Behv, ymin = asymp.LCL, lower = `25th`, middle = mean, upper = `75th`, ymax = asymp.UCL)) +
  geom_boxplot(stat = "identity")+
  theme_minimal()
```
# plots for Layer stats

```{r}

emmeans_Layer_simp <- emmeans::emmeans(mod3, ~ Layer , type = "response")
Layercon_simp <- emmeans::emmeans(mod3, pairwise ~ Layer)
# Convert to tibble
pdata <- emmeans_Layer_simp %>% as_tibble() 
pdata <- pdata %>% mutate(Layer = trimws(as.character(Layer)))

# Prepare p-values
pvals <- Layercon_simp$contrasts %>%
  as_tibble() %>%
  separate_wider_delim(contrast, names = c("group1", "group2"), delim = "-") %>%
  mutate(psig = case_when(
    p.value < 0.001 ~'***',
    p.value < 0.01 ~'**',
    p.value < 0.05 ~'*',
     p.value > 0.05  ~'NS',
  )) %>% mutate( group1 = 'L2/3')%>%
  mutate(group1 = as.character(group1), group2 = as.character(group2))  %>% mutate(group1 = trimws(group1), group2 = trimws(group2)) %>%  # Ensure character type
  left_join(pdata %>% mutate(Layer = as.character(Layer)), 
            by = join_by(group1 ==Layer))
# Plot
ggplot(pdata %>% mutate(response = response + min(Test4_org$Zscore)-1, asymp.LCL = asymp.LCL  + min(Test4_org$Zscore)-1, asymp.UCL = asymp.UCL  + min(Test4_org$Zscore)-1), aes(x = Layer, y = response)) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.2) +
  geom_point()+
  geom_text(aes(label = round(response, 2)), hjust = -1) +
  theme_minimal()+
  ylab('max Zscore response')+
  ggpubr::stat_pvalue_manual(pvals %>% mutate(response = response + min(Test4_org$Zscore)-1, asymp.LCL = asymp.LCL  + min(Test4_org$Zscore)-1, asymp.UCL = asymp.UCL  + min(Test4_org$Zscore)-1, y.position = asymp.UCL + 0.5) %>% mutate(y.position = ifelse(group1=='A2L' & group2=='W2T', y.position+0.5,y.position)), label = "psig", 
                             xmin = "group1", xmax = "group2", y.position = "y.position")+
  coord_fixed(ratio=1)
#ggsave('C:/users/Freitag/Desktop/Layer_stats.tiff', bg= 'white',dpi=900)



pvals %>% mutate(response = response + min(Test4_org$Zscore)-1, asymp.LCL = asymp.LCL  + min(Test4_org$Zscore)-1, asymp.UCL = asymp.UCL  + min(Test4_org$Zscore)-1, y.position = asymp.UCL + 0.5) %>% mutate(y.position = ifelse(group1=='A2L' & group2=='W2T', y.position+0.5,y.position))

```


`



